version: '3.5'
# 网络配置
networks:
  backend:
    driver: bridge

# 服务容器配置
services:
  user-api: # 自定义容器名称
    build:
      context: EduGrad                # 指定整个服务所属的根目录   
      dockerfile: user/api/Dockerfile # 指定根目录下 具体api或rpc的 Dockerfile文件
    environment: # 设置环境变量
      - TZ=Asia/Shanghai
    volumes:
      - /www/wwwroot/mediaFile:/app/goFile
    privileged: true
    ports: # 设置端口映射
      - "8888:8888"  
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - backend
    # restart: always                # 指定容器退出后的重启策略为始终重启
  
  user-rpc:
    build:
      context: EduGrad                 
      dockerfile: user/rpc/Dockerfile
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /www/wwwroot/mediaFile:/app/goFile
    privileged: true
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    networks:
      - backend
    # restart: always

  paper-api: # 自定义容器名称
    build:
      context: EduGrad                # 指定整个服务所属的根目录   
      dockerfile: paper/api/Dockerfile # 指定根目录下 具体api或rpc的 Dockerfile文件
    environment: # 设置环境变量
      - TZ=Asia/Shanghai
    volumes:
      - /www/wwwroot/mediaFile:/app/goFile
    privileged: true
    ports: # 设置端口映射
      - "8889:8889"  
    stdin_open: true                     # 打开标准输入，可以接受外部输入
    tty: true
    networks:
      - backend
    # restart: always                # 指定容器退出后的重启策略为始终重启
  
  paper-rpc:
    build:
      context: EduGrad                 
      dockerfile: paper/rpc/Dockerfile
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /www/wwwroot/mediaFile:/app/goFile
    privileged: true
    ports:
      - "8890:8890"
    stdin_open: true
    tty: true
    networks:
      - backend
    # restart: always
